# Generated by Django 4.2.10 on 2024-03-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pin_code',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='departement',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
