# Generated by Django 4.2.10 on 2024-03-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_pin_code_userprofile_departement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rue',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
