# Generated by Django 4.2.10 on 2024-03-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofile_state_userprofile_rue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rue',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
